cluster:
  id: home-lab

coordinator:
  id: main
  config_version: 1

  http:
    listen_addr: 0.0.0.0:8080

  grpc:
    listen_addr: 0.0.0.0:9090

  endpoints:
    - name: local
      kind: grpc
      address: 127.0.0.1:9090
      scope: same-host
      priority: 10
    - name: vmware
      kind: grpc
      address: 192.168.159.1:9090
      scope: vmware-vmnet
      priority: 20